"""create user model

Revision ID: 33e17c0fea06
Revises: 
Create Date: 2024-06-30 04:13:42.270430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e17c0fea06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_resources_id'), 'human_resources', ['id'], unique=False)
    op.create_table('part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_id'), 'part', ['id'], unique=False)
    op.create_table('recruitment',
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['human_resources.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('human_id', 'part_id')
    )
    op.create_index(op.f('ix_recruitment_human_id'), 'recruitment', ['human_id'], unique=False)
    op.create_index(op.f('ix_recruitment_part_id'), 'recruitment', ['part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruitment_part_id'), table_name='recruitment')
    op.drop_index(op.f('ix_recruitment_human_id'), table_name='recruitment')
    op.drop_table('recruitment')
    op.drop_index(op.f('ix_part_id'), table_name='part')
    op.drop_table('part')
    op.drop_index(op.f('ix_human_resources_id'), table_name='human_resources')
    op.drop_table('human_resources')
    # ### end Alembic commands ###
